# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Java 25 da Microsoft instalado pelo Minecraft
org.gradle.java.home=D:/Minecraft/.minecraft/runtime/java-runtime-epsilon/windows/java-runtime-epsilon

# Environment Properties
minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.48-beta

## Mod Properties
mod_id=wingsofthewild
mod_name=Wings of the Wild
mod_license=All Rights Reserved
mod_version=1.0.2
mod_group_id=com.wingsofthewild
